### ISSUE TITLE
Swapping items in inventory while a "Use" action is pending can cause TypeError

### ISSUE THREAD

**Issue by Cyborger1** [genfanad/genfanad-public-bugtracker#137]
If you select an item to "Use" in your inventory, then swap items around, the indicator for the pending item to be used is not swapped/updated accordingly.

Knowing this, it's possible to swap the item out of the slot, leaving it empty. This causes the game to freak out because it's trying to render the possible action of using an item from an empty slot.

Use an item:
![image](https://user-images.githubusercontent.com/45152844/224378795-e352567c-26d6-4480-b894-04ecadeeca36.png)

Move it out of the slot:
![image](https://user-images.githubusercontent.com/45152844/224378865-323fd581-927a-473f-b5db-d0d9da2cddb0.png)

Game window freezes, this gets spammed in the dev console every frame:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'item')
    at Inventory.selectedName (ui_inventory.js:6:142)
    at updateMouseSelectForInventory (items.js:85:272)
    at updateContextOptions (mouse.js:34:145)
    at animate (client.js:11:371)
```

Quick fix, add a guard clause to prevent the game window from freezing.
```js
selectedName() {
    if (this.selected === undefined)
        return;
    let item_stack = this.items[this.selected];
    if (item_stack === undefined)
        return;
    return "<span class='item'>" + itemName(item_stack.item) + "</span>";
}
```

Ideally however, swapping around items in the inventory should clear the selected item, or clear the selection if the slot ever becomes empty.

**Comment by Cyborger1** [comment]
Similarly, the `selectSlot()` function could use a similar safeguard, as it's possible to move items out of the way while the context menu is open and trigger the bug.

![image](https://user-images.githubusercontent.com/45152844/224427327-e0c91b08-bc96-4525-b011-c70422bf05a7.png)

Quick fix:
```js
selectSlot(slot) {
    if (this.selected !== undefined)
        return;
    if (this.items[slot] === undefined) // Prevent selecting an empty slot
        return;
    this.selected = slot;
    let DOM_slot = this.DOM_slots[slot].item_div;
    DOM_slot.classList.add('inventory_selected');
}
```

**Comment by Cyborger1** [comment]
The bug can still occur when performing actions that remove items from the inventory.
![image](https://user-images.githubusercontent.com/45152844/227540150-2a6a3262-914e-488d-b92a-2d5635686f46.png)

For example, selecting an ore when forging bronze bars:
![image](https://user-images.githubusercontent.com/45152844/227540549-44b1de60-6cc4-4ca4-8a5d-b75d5085b7dd.png)

This will lead to the 3d view freezing again, however the selection is cleared once the bars are done smelting and the game returns to normal.
